name: Sync Nigthly to Nexus Branch
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge nightly -> nexus
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: nightly
          target_branch: nexus
          github_token: ${{ github.token }}
